# authentication error messages
authentication.err.validation.authenticator.notfound=Falha ao autenticar. O autenticador com o nome {0} n\u00e3o foi encontrado
authentication.err.validation.authenticator.notactive=O autenticador n\u00e3o est\u00e1 ativo

authentication.err.authentication=Falha ao autenticar. O nome de usu\u00e1rio ou a senha est\u00e1 errado. Nome do usu\u00e1rio:{0} Raz\u00e3o {1}
authentication.err.connection=Falha ao se conectar a {0}. Raz\u00e3o {1}
authentication.err.communication=Falha ao se comunicar com {0}. Raz\u00e3o {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Falha ao se conectar. O host LDAP {0} \u00e9 desconhecido
authentication.err.connection.ldap.user.notfound=Usu\u00e1rio LDAP {0} n\u00e3o encontrado
authentication.err.connection.ldap.manager.notfound=Usu\u00e1rio do gerenciador LDAP {0} n\u00e3o encontrado
authentication.err.connection.ldap.search=N\u00e3o \u00e9 poss\u00edvel pesquisar o LDAP. Raz\u00e3o {0}

# PASSTHRU
authentication.err.connection.passthru.server=Falha ao abrir a sess\u00e3o para o servidor de passagem
authentication.err.passthru.token.unsupported=Tipo de token de autentica\u00e7\u00e3o n\u00e3o suportado
authentication.err.passthru.guest.notenabled=Logons de convidado desativados
authentication.err.passthru.user.disabled=Conta desativada
authentication.err.passthru.user.notfound=Usu\u00e1rio de passagem {0} n\u00e3o encontrado

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Valida\u00e7\u00e3o de solicita\u00e7\u00e3o
authentication.step.ldap.connecting=Conectando-se ao servidor LDAP {0} 
authentication.step.ldap.connected=Conectado ao servidor LDAP {0} com o principal: {1}
authentication.step.ldap.lookup=Pesquisa de userId do usu\u00e1rio de teste:{0} com consulta: {1}
authentication.step.ldap.lookedup=Pesquisou a userId do usu\u00e1rio de teste:{0}, encontrou um nome distinto (DN):{1}
authentication.step.ldap.format.user=Formato de nome do usu\u00e1rio especificado, userNameFormat:{2} Formatar userId de usu\u00e1rio:{0} para criar um nome distinto (DN):{1}
authentication.step.ldap.authentication=Autenticar userId:{0}


# Sync Summary message 
synchronization.summary.status={0} usu\u00e1rio(s) e {1} grupo(s) processado(s)


# Error messages
authentication.ldap.validation.authenticator.notfound=Autenticador n\u00e3o encontrado

# Synchronization Diagnostic Steps
synchronization.step.users=Encontrados {0} usu\u00e1rios
synchronization.step.groups=Encontrados {0} grupos
synchronization.step.users.lastsynced=\u00daltimos usu\u00e1rios sincronizados com sucesso {0}
synchronization.step.groups.lastsynced=\u00daltimos grupos sincronizados com sucesso {0}

synchronization.err.ldap.search=Erro durante a pesquisa de LDAP. Raz\u00e3o:{0}
synchronization.err.ldap.get.user.id.missing=Usu\u00e1rio com DN de atributo de ID de usu\u00e1rio ausente = {0}, attributeName = {1})
synchronization.err.ldap.get.group.id.missing=Grupo com DN de atributo de ID de usu\u00e1rio ausente = {0}, attributeName = {1})

synchronization.err.ldap.search.base.invalid=Base de pesquisa {0} inv\u00e1lida, raz\u00e3o: {1}

synchronization.err.ldap.group.member.missing.exception=''Falha ao resolver membro do grupo {0} com nome distinto: {1}, raz\u00e3o {2}).
synchronization.err.ldap.group.member.missing=''Falha ao resolver membro do grupo {0} com nome distinto: {1}).



       



